import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter, Poppins, Roboto } from 'next/font/google'
import Footer from '@/components/Footer'
import Provider from '@/providers/Provider'

const inter = Poppins({ subsets: ['latin'],weight:["300","500","700"] })

export const metadata = {
  title: 'NEXT Crash Course',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
      <Navbar/>
      {children}
      <Footer/>
      </Provider>
      </body>
    </html>
  )
}
